service: lambda-demo
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  region: ap-south-1
  runtime: nodejs16.x

functions:
  main:
    handler: dist/index.default
    events:
      - httpApi: '*'

custom:
  serverless-offline:
    httpPort: 8080
    lambdaPort: 9000

plugins:
  - serverless-offline
